dist: xenial

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - export CC=gcc-7
  - export CXX=g++-7

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - echo "Starting build in `pwd`"
  - mkdir build
  - cd build
  - cmake ..
  - make